### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jamesdixon**
Hi,

This PR does the following:
- updates package to use the latest 0.6.x node-rollbar release
- updates hapi lab/code dependencies
- updates travis to test on node 4/6 (these are the versions hapi _officially_ supports)
- removed unnecessary harmony flags when testing
- fixed an issue where the linter was complaining that const was a reserved keyword (see [this thread](https://github.com/hapijs/lab/issues/526#issuecomment-186664881))

Thanks!

### CODE REVIEW

**Comment by jamesdixon** [comment]
@jmonster would you be able to take a quick look at this and let me know if there is anything you feel should be changed?

**Comment by jmonster** [comment]
hey, thank you so much for the PR! I haven't had a chance but I am very excited -- don't take my silence as a 👎 I'll try to get to this soon

**Comment by jamesdixon** [comment]
No worries! Just wanted to make sure someone was behind the curtain 👍

**Comment by jmonster** [comment]
awesome! 💯  thank you!

**Comment by jmonster** [comment]
https://github.com/yayuhh/icecreambar/releases/tag/v3.2.0

**Comment by jamesdixon** [comment]
Thanks!

**Pull request merged**
